server:
  port: 9880

zuul:
  routes:
    gwas-rest:
      path: /gwas/rest/**
      url: http://snoopy.ebi.ac.uk:9882/gwas/rest

    gwas-ui:
      path: /gwas/**
      url: http://snoopy.ebi.ac.uk:9881/gwas

