server:
  port: 9780

zuul:
  routes:
    gwas-rest:
      path: /gwas/rest/**
      url: http://snoopy.ebi.ac.uk:9782/gwas/rest

    gwas-ui:
      path: /gwas/**
      url: http://snoopy.ebi.ac.uk:9781/gwas

